---
title: Benchmark for `predped` 
author: Niels Vanhasbroeck
date: "`r Sys.Date()`"
output: pdf_document
---
```{r Load in package and create function for benchmark, include = FALSE, echo = FALSE, warning = FALSE}

devtools::load_all()
library(tidyverse)

# Create the basic function to be used to investigate the benchmark
test_times <- function(fx) {
    times <- numeric(10)
    for(i in seq_along(times)) {
        start_time <- Sys.time()
        fx()
        stop_time <- Sys.time()
        times[i] <- stop_time - start_time
    }
    return(quantile(times, probs = c(0.025, 0.5, 0.975)))
}

# Show numbers in scientific digits
rnd <- function(x) {
    return(format(x, scientific = TRUE, digits = 2))
}

```

```{r general, child = "files/benchmark_general.Rmd", warning = F}
```

```{r goals, child = "files/benchmark_goals.Rmd", warning = F}
```

```{r moving_options, child = "files/benchmark_moving_options.Rmd", warning = F}
```

```{r objects, child = "files/benchmark_objects.Rmd", warning = F}
```

```{r route, child = "files/benchmark_routing.Rmd", warning = F}
```


