# route.R 

```{r routing setup, echo = FALSE}

# Create setting
setting <- background(shape = rectangle(center = c(20, 12.5),
                                        size = c(40, 25)), 
                      objects = list(# Special shelves
                                     rectangle(center = c(20, 1.2 / 2), 
                                               size = c(32, 1.2), 
                                               interactable = TRUE),
                                     rectangle(center = c(38, 4),
                                               size = c(1.2, 4),
                                               interactable = TRUE),
                                     rectangle(center = c(39.4, 7.5 + 8.75), 
                                               size = c(1.2, 25 - 7.5), 
                                               interactable = TRUE),
                                     polygon(points = rbind(c(0, 19.5),
                                                            c(0, 25),
                                                            c(16, 25),
                                                            c(16, 22.5),
                                                            c(1.2, 22.5),
                                                            c(1.2, 19.5)),
                                             interactable = TRUE),
                                     rectangle(center = c(1, 14.5),
                                               size = c(2, 1.2),
                                               interactable = TRUE),
                                     polygon(points = rbind(c(0, 3.5), 
                                                            c(0, 11.6),
                                                            c(17, 11.6),
                                                            c(17, 10.4),
                                                            c(1.2, 10.4),
                                                            c(1.2, 3.5)),
                                             interactable = TRUE),
                                     # Bottom left
                                     rectangle(center = c(12, 4),
                                               size = c(12, 1.2),
                                               interactable = TRUE),
                                     rectangle(center = c(12, 7),
                                               size = c(12, 1.2),
                                               interactable = TRUE),
                                     # Top left
                                     rectangle(center = c(12.5, 14),
                                               size = c(13, 1.2),
                                               interactable = TRUE),
                                     rectangle(center = c(12.5, 17),
                                               size = c(13, 1.2),
                                               interactable = TRUE),
                                     rectangle(center = c(12.5, 20),
                                               size = c(13, 1.2),
                                               interactable = TRUE),
                                     # Top right
                                     rectangle(center = c(29, 11),
                                               size = c(14, 1.2),
                                               interactable = TRUE),
                                     rectangle(center = c(29, 14),
                                               size = c(14, 1.2),
                                               interactable = TRUE),
                                     rectangle(center = c(29, 17),
                                               size = c(14, 1.2),
                                               interactable = TRUE),
                                     rectangle(center = c(29, 20),
                                               size = c(14, 1.2),
                                               interactable = TRUE),
                                     rectangle(center = c(29, 23),
                                               size = c(14, 1.2),
                                               interactable = TRUE),
                                     # Bottom right
                                     rectangle(center = c(27, 4),
                                               size = c(12, 1.2),
                                               interactable = TRUE),
                                     rectangle(center = c(27, 7),
                                               size = c(12, 1.2),
                                               interactable = TRUE)),
                      entrance = c(0, 0.5),
                      exit = c(0, 13),
                      same_exit = FALSE)

# Precompute some edges
few_edges <- predped::create_edges(c(0.3, 0.5), c(0, 13), setting, many_options = FALSE)
many_edges <- predped::create_edges(c(0.3, 0.5), c(0, 13), setting, many_options = TRUE)

few_edges$edges <- few_edges$edges[!(few_edges$edges$from %in% c("agent", "goal")),]
few_edges$edges <- few_edges$edges[!(few_edges$edges$to %in% c("agent", "goal")),]
few_edges$nodes <- few_edges$nodes[!(few_edges$nodes$node_ID %in% c("agent", "goal")),]

many_edges$edges <- many_edges$edges[!(many_edges$edges$from %in% c("agent", "goal")),]
many_edges$edges <- many_edges$edges[!(many_edges$edges$to %in% c("agent", "goal")),]
many_edges$nodes <- many_edges$nodes[!(many_edges$nodes$node_ID %in% c("agent", "goal")),]

```

## adjust_edges

```{r routing adjust_edges, echo = FALSE, results = "asis"}

# Test `adjust_edges`
set.seed(1)
new_agents <- lapply(1:10,
                     \(x) predped::agent(center = runif(2, 1, 20), radius = 0.25))
new_setting <- setting 
objects(new_setting) <- append(objects(new_setting), new_agents)

fr <- (\() predped::adjust_edges(c(0.3, 0.5), 
                                 c(0, 13), 
                                 new_setting, 
                                 new_objects = new_agents,
                                 precomputed_edges = few_edges, 
                                 reevaluate = TRUE)) |>
    test_times() |>
    rnd()

mr <- (\() predped::adjust_edges(c(0.3, 0.5), 
                                 c(0, 13), 
                                 new_setting, 
                                 new_objects = new_agents,
                                 precomputed_edges = many_edges, 
                                 reevaluate = TRUE)) |>
    test_times() |>
    rnd()

fn <- (\() predped::adjust_edges(c(0.3, 0.5), 
                                 c(0, 13), 
                                 new_setting, 
                                 new_objects = new_agents,
                                 precomputed_edges = few_edges, 
                                 reevaluate = FALSE)) |>
    test_times() |>
    rnd()

mn <- (\() predped::adjust_edges(c(0.3, 0.5), 
                                 c(0, 13), 
                                 new_setting, 
                                 new_objects = new_agents,
                                 precomputed_edges = many_edges, 
                                 reevaluate = FALSE)) |>
    test_times() |>
    rnd()

# Create a table displaying these results
tbl <- cbind(c("Few edges", "Many edges"), 
             c(fr[2], mr[2]), 
             c(paste0("[", fr[1], ",", fr[3], "]"), paste0("[", mr[1], ",", mr[3], "]")), 
             c(fn[2], mn[2]), 
             c(paste0("[", fn[1], ",", fn[3], "]"), paste0("[", mn[1], ",", mn[3], "]")))
rownames(tbl) <- NULL


# Define the caption for the table 
caption <- paste0("Benchmark for the adjust\\_edges function. ", 
                  "Options were to check whether the precomputed edges passed through objects or not ",
                  "(reevaluate = TRUE or FALSE resp.). ",
                  "Additionally, benchmark times are given for the case where you only have few edges ",
                  "or many edges in the precomputed edges variable. ",
                  "For this benchmark, we added 10 agents to the environment ad random.")

# Print the table so that it can be printed in text
tbl %>% 
    knitr::kable(format = "latex", 
                 align = "lllll",
                 caption = caption,
                 longtable = FALSE,
                 booktabs = TRUE,
                 escape = FALSE,  
                 position = "H" ) %>% 
    kableExtra::add_header_above(c(" " = 1, "reevaluate = TRUE" = 2, "reevaluate = FALSE" = 2)) %>% 
    print()

```

## combine_nodes

```{r routing combine_nodes, echo = FALSE, results = "asis"}

# Test 
nodes <- data.frame(node_ID = paste0("node_", 1:100), 
                    X = 1:100, 
                    Y = 1:100)

single <- (\() predped:::combine_nodes(nodes)) |>
    test_times() |>
    rnd()

pair <- (\() predped:::combine_nodes(nodes, nodes)) |>
    test_times() |>
    rnd()

# Create a table displaying these results
tbl <- c(single[2], 
         paste0("[", single[1], ",", single[3], "]"), 
         pair[2],
         paste0("[", pair[1], ",", pair[3], "]")) |>
    matrix(nrow = 1)
rownames(tbl) <- NULL


# Define the caption for the table 
caption <- paste0("Benchmark for the combine\\_nodes function. ", 
                  "Distinction is made between using a single or a pair of matrices. ",
                  "For this benchmark, each matrix consisted of 100 nodes.")

# Print the table so that it can be printed in text
tbl %>% 
    knitr::kable(format = "latex", 
                 align = "lllll",
                 caption = caption,
                 longtable = FALSE,
                 booktabs = TRUE,
                 escape = FALSE,  
                 position = "H" ) %>% 
    kableExtra::add_header_above(c("1 matrix" = 2, "2 matrices" = 2)) %>% 
    print()

```

## create_edges
```{r routing create_edges, echo = FALSE, results = "asis"}

# Test `create_edges`
f <- (\() predped::create_edges(c(0.3, 0.5), 
                                c(0, 13), 
                                setting, 
                                many_options = FALSE)) |>
    test_times() |>
    rnd()

m <- (\() predped::create_edges(c(0.3, 0.5), 
                                c(0, 13), 
                                setting, 
                                many_options = TRUE)) |>
    test_times() |>
    rnd()

fa <- (\() predped::create_edges(c(0.3, 0.5), 
                                 c(0, 13), 
                                 new_setting, 
                                 many_options = FALSE)) |>
    test_times() |>
    rnd()

ma <- (\() predped::create_edges(c(0.3, 0.5), 
                                 c(0, 13), 
                                 new_setting, 
                                 many_options = TRUE)) |>
    test_times() |>
    rnd()

# Create a table displaying these results
tbl <- cbind(c("Few edges", "Many edges"),
             c(f[2], m[2]),
             c(paste0("[", f[1], ",", f[3], "]"), paste0("[", m[1], ",", m[3], "]")),
             c(fa[2], ma[2]),
             c(paste0("[", fa[1], ",", fa[3], "]"), paste0("[", ma[1], ",", ma[3], "]"))) 
rownames(tbl) <- NULL


# Define the caption for the table 
caption <- paste0("Benchmark for the create\\_edges function. ", 
                  "Benchmark is computed for few and many possible edges (many\\_options = FALSE or TRUE resp.). ",
                  "For a comparison with `adjust\\_edges`, we run this once with and without 10 additional agents in the background.")

# Print the table so that it can be printed in text
tbl %>% 
    knitr::kable(format = "latex", 
                 align = "llll",
                 caption = caption,
                 longtable = FALSE,
                 booktabs = TRUE,
                 escape = FALSE,  
                 position = "H" ) %>% 
    kableExtra::add_header_above(c(" " = 1, "No additional agents" = 2, "Additional agents" = 2)) %>% 
    print()
```

## create_nodes

```{r routing create_nodes, echo = FALSE, results = "asis"}

# Test `create_nodes`
f <- (\() predped::create_nodes(c(0.3, 0.5), 
                                c(0, 13), 
                                setting, 
                                many_options = FALSE)) |>
    test_times() |>
    rnd()

m <- (\() predped::create_nodes(c(0.3, 0.5), 
                                c(0, 13), 
                                setting, 
                                many_options = TRUE)) |>
    test_times() |>
    rnd()

# Create a table displaying these results
tbl <- c(f[2], 
         paste0("[", f[1], ",", f[3], "]"), 
         m[2], 
         paste0("[", m[1], ",", m[3], "]")) %>% 
    matrix(nrow = 1)
rownames(tbl) <- NULL


# Define the caption for the table 
caption <- paste0("Benchmark for the create\\_nodes function. ", 
                  "Benchmark is computed for few and many possible edges (many\\_options = FALSE or TRUE resp.).")

# Print the table so that it can be printed in text
tbl %>% 
    knitr::kable(format = "latex", 
                 align = "lll",
                 caption = caption,
                 longtable = FALSE,
                 booktabs = TRUE,
                 escape = FALSE,  
                 position = "H" ) %>% 
    kableExtra::add_header_above(c("many\\_options = FALSE" = 2, "many\\_options = TRUE" = 2)) %>% 
    print()
```

## evaluate_edges

```{r routing evaluate_edges, echo = FALSE, results = "asis"}

# Test `create_edges`
segments <- subset(few_edges$edges_with_coords, select = -cost)
f <- (\() predped::evaluate_edges(segments, 
                                  predped::objects(setting))) |>
    test_times() |>
    rnd()

segments <- subset(many_edges$edges_with_coords, select = -cost)
m <- (\() predped::evaluate_edges(segments, 
                                  predped::objects(setting))) |>
    test_times() |>
    rnd()

# Create a table displaying these results
tbl <- c(f[2], 
         paste0("[", f[1], ",", f[3], "]"), 
         m[2], 
         paste0("[", m[1], ",", m[3], "]")) %>% 
    matrix(nrow = 1)
rownames(tbl) <- NULL


# Define the caption for the table 
caption <- paste0("Benchmark for the evaluate\\_edges function. ", 
                  "Benchmark is computed for few and many possible edges.")

# Print the table so that it can be printed in text
tbl %>% 
    knitr::kable(format = "latex", 
                 align = "lll",
                 caption = caption,
                 longtable = FALSE,
                 booktabs = TRUE,
                 escape = FALSE,  
                 position = "H" ) %>% 
    kableExtra::add_header_above(c("Few edges" = 2, "Many edges" = 2)) %>% 
    print()
```

## prune_edges

```{r routing prune_edges, echo = FALSE, results = "asis"}

# Create all objects
segments <- cbind(rep(1, 100), rep(1, 100), rep(20, 100), rep(20, 100))
obj <- predped::objects(setting)

# Perform the test
caption <- paste0("Benchmark for the prune\\_edges function. ", 
                  "Benchmark is computed for 100 segments that are checked in this function.")
tbl <- (\() predped:::prune_edges(obj, segments)) |>
    test_times() |>
    rnd() |>
    matrix(nrow = 1)
colnames(tbl) <- c("2.5\\%", "50\\%", "95\\%")

tbl |>
    knitr::kable(format = "latex", 
                 align = "lll",
                 caption = caption,
                 longtable = FALSE,
                 booktabs = TRUE,
                 escape = FALSE,  
                 position = "H" ) |>
    print()
```