# objects.R 

## add_nodes 

```{r objects add_nodes, echo = FALSE, results = "asis"}

# Initialize the objects 
obj <- list(predped:::rectangle(center = c(1, 2), size = c(1, 1)),
            predped:::circle(center = c(1, 2), radius = 1),
            predped:::polygon(points = rbind(c(1, 1), c(1, -1), c(-1, -1), c(-1, 1)))) 

# Test
r <- (\() predped::add_nodes(obj[[1]], space_between = 0.5, only_corners = TRUE)) |>
    test_times() |>
    rnd() 
c <- (\() predped::add_nodes(obj[[2]], space_between = 0.5, only_corners = TRUE)) |>
    test_times() |>
    rnd() 
p <- (\() predped::add_nodes(obj[[3]], space_between = 0.5, only_corners = TRUE)) |>
    test_times() |>
    rnd() 

rf <- (\() predped::add_nodes(obj[[1]], space_between = 0.5, only_corners = FALSE)) |>
    test_times() |>
    rnd() 
cf <- (\() predped::add_nodes(obj[[2]], space_between = 0.5, only_corners = FALSE)) |>
    test_times() |>
    rnd() 
pf <- (\() predped::add_nodes(obj[[3]], space_between = 0.5, only_corners = FALSE)) |>
    test_times() |>
    rnd() 

# Create the table
tbl <- cbind(c("only\\_corners = TRUE", "only\\_corners = FALSE"),
             c(r[2], rf[2]),
             c(paste0("[", r[1], ",", r[3], "]"), paste0("[", rf[1], ",", rf[3], "]")),
             c(p[2], pf[2]),
             c(paste0("[", p[1], ",", p[3], "]"), paste0("[", pf[1], ",", pf[3], "]")),
             c(c[2], cf[2]),
             c(paste0("[", c[1], ",", c[3], "]"), paste0("[", cf[1], ",", cf[3], "]")))
rownames(tbl) <- NULL

# Write the caption
caption <- paste0("Benchmark for the add\\_nodes method for objects. ",
                  "Distinctions are made between the different objects that are exported by predped. ", 
                  "Here, we also distinguish between having only corner nodes created, or whether nodes should exist ",
                  "on the complete circumference of the object.")
tbl |>
    knitr::kable(format = "latex", 
                 align = "lll",
                 caption = caption,
                 longtable = FALSE,
                 booktabs = TRUE,
                 escape = FALSE,  
                 position = "H" ) |>
    kableExtra::add_header_above(c(" " = 1, "Rectangle" = 2, "Polygon" = 2, "Circle" = 2)) |>
    print()

```

## in_object

```{r objects in_object, echo = FALSE, results = "asis"}

# Initialize the objects 
obj <- list(predped:::rectangle(center = c(1, 2), size = c(1, 1)),
            predped:::circle(center = c(1, 2), radius = 1),
            predped:::polygon(points = rbind(c(1, 1), c(1, -1), c(-1, -1), c(-1, 1)))) 
pts <- cbind(rep(1, 100), rep(2, 100))

# Test
r <- (\() predped::in_object(obj[[1]], pts)) |>
    test_times() |>
    rnd() 
c <- (\() predped::in_object(obj[[2]], pts)) |>
    test_times() |>
    rnd() 
p <- (\() predped::in_object(obj[[3]], pts)) |>
    test_times() |>
    rnd() 

# Create the table
tbl <- c(r[2], c(paste0("[", r[1], ",", r[3], "]")), 
         p[2], c(paste0("[", p[1], ",", p[3], "]")), 
         c[2], c(paste0("[", c[1], ",", c[3], "]"))) |>
    matrix(nrow = 1)
colnames(tbl) <- NULL

# Write the caption
caption <- paste0("Benchmark for the in\\_object method for objects. ",
                  "Distinctions are made between the different objects that are exported by predped. ",
                  "For this benchmark, 100 points are evaluated.")
tbl |>
    knitr::kable(format = "latex", 
                 align = "lll",
                 caption = caption,
                 longtable = FALSE,
                 booktabs = TRUE,
                 escape = FALSE,  
                 position = "H" ) |>
    kableExtra::add_header_above(c("Rectangle" = 2, "Polygon" = 2, "Circle" = 2)) |>
    print()

```

## initialize

```{r objects initialize, echo = FALSE, results = "asis"}

# Test 
pts <- rbind(c(1, 1), c(1, -1), c(-1, -1), c(-1, 1))
r <- (\() predped:::rectangle(center = c(1, 2), size = c(1, 1))) |>
    test_times() |>
    rnd() 
c <- (\() predped:::circle(center = c(1, 2), radius = 1)) |>
    test_times() |>
    rnd() 
p <- (\() predped:::polygon(points = pts)) |>
    test_times() |>
    rnd() 

# Create the table
tbl <- c(r[2], c(paste0("[", r[1], ",", r[3], "]")), 
         p[2], c(paste0("[", p[1], ",", p[3], "]")), 
         c[2], c(paste0("[", c[1], ",", c[3], "]"))) |>
    matrix(nrow = 1)
colnames(tbl) <- NULL

# Write the caption
caption <- paste0("Benchmark for the initialize function, that is, for initializing one of the objects. ",
                  "Distinctions are made between the different objects that are exported by predped.")
tbl |>
    knitr::kable(format = "latex", 
                 align = "lll",
                 caption = caption,
                 longtable = FALSE,
                 booktabs = TRUE,
                 escape = FALSE,  
                 position = "H" ) |>
    kableExtra::add_header_above(c("Rectangle" = 2, "Polygon" = 2, "Circle" = 2)) |>
    print()

```

## intersects 

```{r objects intersects, echo = FALSE, results = "asis"}

# Initialize the objects 
obj <- list(predped:::rectangle(center = c(1, 2), size = c(1, 1)),
            predped:::circle(center = c(1, 2), radius = 1),
            predped:::polygon(points = rbind(c(1, 1), c(1, -1), c(-1, -1), c(-1, 1)))) 

# Test
rr <- (\() predped::intersects(obj[[1]], obj[[1]])) |>
    test_times() |>
    rnd() 
rc <- (\() predped::intersects(obj[[1]], obj[[2]])) |>
    test_times() |>
    rnd() 
rp <- (\() predped::intersects(obj[[1]], obj[[3]])) |>
    test_times() |>
    rnd() 

cr <- (\() predped::intersects(obj[[2]], obj[[1]])) |>
    test_times() |>
    rnd() 
cc <- (\() predped::intersects(obj[[2]], obj[[2]])) |>
    test_times() |>
    rnd() 
cp <- (\() predped::intersects(obj[[2]], obj[[3]])) |>
    test_times() |>
    rnd() 

pr <- (\() predped::intersects(obj[[3]], obj[[1]])) |>
    test_times() |>
    rnd() 
pc <- (\() predped::intersects(obj[[3]], obj[[2]])) |>
    test_times() |>
    rnd() 
pp <- (\() predped::intersects(obj[[3]], obj[[3]])) |>
    test_times() |>
    rnd() 

# Create the table
tbl <- cbind(c("Rectangle", "Polygon", "Circle"),
             c(rr[2], pr[2], cr[2]),
             c(paste0("[", rr[1], ",", rr[3], "]"), paste0("[", pr[1], ",", pr[3], "]"), paste0("[", cr[1], ",", cr[3], "]")),
             c(rp[2], pp[2], cp[2]),
             c(paste0("[", rp[1], ",", rp[3], "]"), paste0("[", pp[1], ",", pp[3], "]"), paste0("[", cp[1], ",", cp[3], "]")),
             c(rc[2], pc[2], cc[2]),
             c(paste0("[", rp[1], ",", rp[3], "]"), paste0("[", pc[1], ",", pc[3], "]"), paste0("[", cc[1], ",", cc[3], "]")))
rownames(tbl) <- NULL

# Write the caption
caption <- paste0("Benchmark for the intersects method for objects. ",
                  "Distinctions are made between the different objects that are exported by predped. ")
tbl |>
    knitr::kable(format = "latex", 
                 align = "lllllll",
                 caption = caption,
                 longtable = FALSE,
                 booktabs = TRUE,
                 escape = FALSE,  
                 position = "H" ) |>
    kableExtra::add_header_above(c("First object" = 1, "Rectangle" = 2, "Polygon" = 2, "Circle" = 2)) |>
    kableExtra::add_header_above(c(" " = 1, "Second object" = 6)) |>
    print()

```

## line_intersection

```{r objects line_intersection, echo = FALSE, results = "asis"}

# Create all objects
segments <- cbind(rep(1, 100), rep(1, 100), rep(20, 100), rep(20, 100))
obj <- list(predped:::rectangle(center = c(1, 2), size = c(1, 1)),
            predped:::circle(center = c(1, 2), radius = 1),
            predped:::polygon(points = rbind(c(1, 1), c(1, -1), c(-1, -1), c(-1, 1)))) 

# Test
r <- (\() predped::line_intersection(obj[[1]], segments)) |>
    test_times() |>
    rnd()

c <- (\() predped::line_intersection(obj[[2]], segments)) |>
    test_times() |>
    rnd()

p <- (\() predped::line_intersection(obj[[3]], segments)) |>
    test_times() |>
    rnd()

# Perform the test
caption <- paste0("Benchmark for the line\\_intersection method for objects. ", 
                  "Distinctions are made between the different objects that are exported by predped. ",
                  "Benchmark is computed for 100 segments that are checked in this function.")

# Table
tbl <- c(r[2], c(paste0("[", r[1], ",", r[3], "]")), 
         p[2], c(paste0("[", p[1], ",", p[3], "]")), 
         c[2], c(paste0("[", c[1], ",", c[3], "]"))) |>
    matrix(nrow = 1)
colnames(tbl) <- NULL

tbl |>
    knitr::kable(format = "latex", 
                 align = "lll",
                 caption = caption,
                 longtable = FALSE,
                 booktabs = TRUE,
                 escape = FALSE,  
                 position = "H" ) |>
    kableExtra::add_header_above(c("Rectangle" = 2, "Polygon" = 2, "Circle" = 2)) |>
    print()
```

## rng_point 

```{r objects rng_point, echo = FALSE, results = "asis"}

# Create all objects and peform the tests
obj <- list(predped::rectangle(center = c(0, 0), size = c(1, 1)), 
            predped::circle(center = c(0, 0), radius = 1),
            predped::polygon(points = rbind(c(1, 1), c(1, -1), c(-1, -1), c(-1, 1))))

r <- (\() predped:::rng_point(obj[[1]], middle_edge = FALSE)) |>
    test_times() |>
    rnd()

c <- (\() predped:::rng_point(obj[[2]], middle_edge = FALSE)) |>
    test_times() |>
    rnd()

p <- (\() predped:::rng_point(obj[[3]], middle_edge = FALSE)) |>
    test_times() |>
    rnd()

rm <- (\() predped:::rng_point(obj[[1]], middle_edge = TRUE)) |>
    test_times() |>
    rnd()

cm <- (\() predped:::rng_point(obj[[2]], middle_edge = TRUE)) |>
    test_times() |>
    rnd()

pm <- (\() predped:::rng_point(obj[[3]], middle_edge = TRUE)) |>
    test_times() |>
    rnd()

# Create a table displaying these results
tbl <- cbind(c("middle\\_edge = FALSE", "middle\\_edge = TRUE"),
             c(r[2], rm[2]),
             c(paste0("[", r[1], ",", r[3], "]"), paste0("[", rm[1], ",", rm[3], "]")),
             c(p[2], pm[2]),
             c(paste0("[", p[1], ",", p[3], "]"), paste0("[", pm[1], ",", pm[3], "]")),
             c(c[2], cm[2]),
             c(paste0("[", c[1], ",", c[3], "]"), paste0("[", cm[1], ",", cm[3], "]")))
rownames(tbl) <- NULL


# Define the caption for the table 
caption <- paste0("Benchmark for the rng\\_point method for objects. ", 
                  "Benchmark is computed for each of the possible shapes in predped. ",
                  "Additionally, the effect of setting a goal randomly on the object or taking the middle of ",
                  "an edge is also examined (i.e., when middle\\_edge = TRUE or FALSE)")

# Print the table so that it can be printed in text
tbl %>% 
    knitr::kable(format = "latex", 
                 align = "lllllll",
                 caption = caption,
                 longtable = FALSE,
                 booktabs = TRUE,
                 escape = FALSE,  
                 position = "H" ) %>% 
    kableExtra::add_header_above(c(" " = 1, "Rectangle" = 2, "Polygon" = 2, "Circle" = 2)) %>% 
    print()
```