# general.R

## line_line_intersection

```{r general line_line_intersection, echo = FALSE, results = "asis"}

# Test 
segments_1 <- cbind(rep(1, 100), rep(1, 100), rep(20, 100), rep(20, 100))
segments_2 <- cbind(rep(20, 100), rep(1, 100), rep(1, 100), rep(20, 100))
tbl <- (\() predped:::line_line_intersection(segments_1, segments_2)) |>
    test_times() |>
    rnd() |>
    matrix(nrow = 1)
colnames(tbl) <- c("2.5\\%", "50\\%", "95\\%")


caption <- paste0("Benchmark for the line\\_line\\_intersection function. ",
                  "In this benchmark, we use two matrices of 100 segments.")
tbl |>
    knitr::kable(format = "latex", 
                 align = "lll",
                 caption = caption,
                 longtable = FALSE,
                 booktabs = TRUE,
                 escape = FALSE,  
                 position = "H" ) |>
    print()

```

## perpendicular_orientation

```{r general perpendicular_orientation, echo = FALSE, results = "asis"}

# Prepare everything and test
obj <- list(predped:::rectangle(center = c(1, 2), size = c(1, 1)),
            predped:::polygon(points = rbind(c(1, 1), c(1, -1), c(-1, -1), c(-1, 1))),
            predped:::circle(center = c(1, 2), radius = 1)) 
co <- c(0.1, 0.2)

r <- (\() predped::perpendicular_orientation(obj[[1]], co)) |>
    test_times() |>
    rnd()
p <- (\() predped::perpendicular_orientation(obj[[2]], co)) |>
    test_times() |>
    rnd()
c <- (\() predped::perpendicular_orientation(obj[[3]], co)) |>
    test_times() |>
    rnd()

# Create the table
tbl <- c(r[2], c(paste0("[", r[1], ",", r[3], "]")), 
         p[2], c(paste0("[", p[1], ",", p[3], "]")), 
         c[2], c(paste0("[", c[1], ",", c[3], "]"))) |>
    matrix(nrow = 1)
colnames(tbl) <- NULL

# Write the caption
caption <- paste0("Benchmark for the perpendicular\\_orientation function. ",
                  "Distinctions are made between the different objects that are exported by predped.")
tbl |>
    knitr::kable(format = "latex", 
                 align = "lll",
                 caption = caption,
                 longtable = FALSE,
                 booktabs = TRUE,
                 escape = FALSE,  
                 position = "H" ) |>
    kableExtra::add_header_above(c("Rectangle" = 2, "Polygon" = 2, "Circle" = 2)) |>
    print()

```
