# plot.R 

```{r plot setup, echo = FALSE}
setting <- background(shape = rectangle(center = c(20, 12.5),
                                        size = c(40, 25)), 
                      objects = list(# Special shelves
                                     rectangle(center = c(20, 1.2 / 2), 
                                               size = c(32, 1.2), 
                                               interactable = TRUE),
                                     rectangle(center = c(38, 4),
                                               size = c(1.2, 4),
                                               interactable = TRUE),
                                     rectangle(center = c(39.4, 7.5 + 8.75), 
                                               size = c(1.2, 25 - 7.5), 
                                               interactable = TRUE),
                                     polygon(points = rbind(c(0, 19.5),
                                                            c(0, 25),
                                                            c(16, 25),
                                                            c(16, 22.5),
                                                            c(1.2, 22.5),
                                                            c(1.2, 19.5)),
                                             interactable = TRUE),
                                     rectangle(center = c(1, 14.5),
                                               size = c(2, 1.2),
                                               interactable = TRUE),
                                     polygon(points = rbind(c(0, 3.5), 
                                                            c(0, 11.6),
                                                            c(17, 11.6),
                                                            c(17, 10.4),
                                                            c(1.2, 10.4),
                                                            c(1.2, 3.5)),
                                             interactable = TRUE),
                                     # Bottom left
                                     rectangle(center = c(12, 4),
                                               size = c(12, 1.2),
                                               interactable = TRUE),
                                     rectangle(center = c(12, 7),
                                               size = c(12, 1.2),
                                               interactable = TRUE),
                                     # Top left
                                     rectangle(center = c(12.5, 14),
                                               size = c(13, 1.2),
                                               interactable = TRUE),
                                     rectangle(center = c(12.5, 17),
                                               size = c(13, 1.2),
                                               interactable = TRUE),
                                     rectangle(center = c(12.5, 20),
                                               size = c(13, 1.2),
                                               interactable = TRUE),
                                     # Top right
                                     rectangle(center = c(29, 11),
                                               size = c(14, 1.2),
                                               interactable = TRUE),
                                     rectangle(center = c(29, 14),
                                               size = c(14, 1.2),
                                               interactable = TRUE),
                                     rectangle(center = c(29, 17),
                                               size = c(14, 1.2),
                                               interactable = TRUE),
                                     rectangle(center = c(29, 20),
                                               size = c(14, 1.2),
                                               interactable = TRUE),
                                     rectangle(center = c(29, 23),
                                               size = c(14, 1.2),
                                               interactable = TRUE),
                                     # Bottom right
                                     rectangle(center = c(27, 4),
                                               size = c(12, 1.2),
                                               interactable = TRUE),
                                     rectangle(center = c(27, 7),
                                               size = c(12, 1.2),
                                               interactable = TRUE)),
                      entrance = c(0, 0.5),
                      exit = c(0, 13),
                      same_exit = FALSE)
```

## agent

```{r plot agent, echo = FALSE, results = "asis"}

# Create an agent to plot
my_agent <- predped::agent(center = c(0, 0), 
                           radius = 0.25, 
                           current_goal = predped::goal(position = c(10, 0)))

# Plot them
tbl <- (\() predped:::plot(my_agent)) |>
    test_times() |>
    rnd() |>
    matrix(nrow = 1)
colnames(tbl) <- c("2.5\\%", "50\\%", "95\\%")

# Create table
caption <- paste0("Benchmark for the plot method for agents. ")
tbl |>
    knitr::kable(format = "latex", 
                 align = "lll",
                 caption = caption,
                 longtable = FALSE,
                 booktabs = TRUE,
                 escape = FALSE,  
                 position = "H" ) |>
    print()

```

## background

```{r plot background, echo = FALSE, results = "asis"}

# Plot them
no <- (\() predped:::plot(setting, optimize = FALSE)) |>
    test_times() |>
    rnd() 
op <- (\() predped:::plot(setting)) |>
    test_times() |>
    rnd()
    
# Create the table
tbl <- rbind(c("optimize = TRUE", op[2], paste0("[", op[1], ",", op[3], "]")),
             c("optimize = FALSE", no[2], paste0("[", no[1], ",", no[3], "]")))
rownames(tbl) <- NULL

# Create table
caption <- paste0("Benchmark for the plot method for background. ",
                  "We used the supermarket as the benchmark.")
tbl |>
    knitr::kable(format = "latex", 
                 align = "lll",
                 caption = caption,
                 longtable = FALSE,
                 booktabs = TRUE,
                 escape = FALSE,  
                 position = "H" ) |>
    print()

```

## object

```{r plot object, echo = FALSE, results = "asis"}

# Create the objects to be plotted
my_rectangle <- predped::rectangle(center = c(0, 0), size = c(1, 1))
my_circle <- predped::circle(center = c(0, 0), radius = 1)
my_polygon <- predped::polygon(points = predped::points(my_rectangle))

# Plot them
r <- (\() predped:::plot(my_rectangle)) |>
    test_times() |>
    rnd() 
c <- (\() predped:::plot(my_circle)) |>
    test_times() |>
    rnd() 
p <- (\() predped:::plot(my_polygon)) |>
    test_times() |>
    rnd() 
    
# Create the table
tbl <- c(r[2],  
         paste0("[", r[1], ",", r[3], "]"), 
         p[2], 
         paste0("[", p[1], ",", p[3], "]"),
         c[2],
         paste0("[", c[1], ",", c[3], "]")) |>
    matrix(nrow = 1)
rownames(tbl) <- NULL

# Create table
caption <- paste0("Benchmark for the plot method for background. ",
                  "We used the supermarket as the benchmark.")
tbl |>
    knitr::kable(format = "latex", 
                 align = "lll",
                 caption = caption,
                 longtable = FALSE,
                 booktabs = TRUE,
                 escape = FALSE,  
                 position = "H" ) |>
    kableExtra::add_header_above(c("Rectangle" = 2, "Polygon" = 2, "Circle" = 2)) |>
    print()

```

## state 

```{r plot state, echo = FALSE, results = "asis"}

# Read in the state to plot. 
initial_condition <- readRDS(file.path(".", "benchmark_inx.Rds"))

# Plot them
no <- (\() predped:::plot(initial_condition, optimize = FALSE)) |>
    test_times() |>
    rnd() 
op <- (\() predped:::plot(initial_condition)) |>
    test_times() |>
    rnd()
    
# Create the table
tbl <- rbind(c("optimize = TRUE", op[2], paste0("[", op[1], ",", op[3], "]")),
             c("optimize = FALSE", no[2], paste0("[", no[1], ",", no[3], "]")))
rownames(tbl) <- NULL

# Create table
caption <- paste0("Benchmark for the plot method for state. ",
                  "We used a state of 70 agents in the supermarket as the benchmark.")
tbl |>
    knitr::kable(format = "latex", 
                 align = "lll",
                 caption = caption,
                 longtable = FALSE,
                 booktabs = TRUE,
                 escape = FALSE,  
                 position = "H" ) |>
    print()

```