// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// psUtility
NumericVector psUtility(double a_preferred_speed, double b_preferred_speed, double preferred_speed, double slowing_time, NumericVector current_speed, NumericVector goal_distance);
RcppExport SEXP _predped_psUtility(SEXP a_preferred_speedSEXP, SEXP b_preferred_speedSEXP, SEXP preferred_speedSEXP, SEXP slowing_timeSEXP, SEXP current_speedSEXP, SEXP goal_distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a_preferred_speed(a_preferred_speedSEXP);
    Rcpp::traits::input_parameter< double >::type b_preferred_speed(b_preferred_speedSEXP);
    Rcpp::traits::input_parameter< double >::type preferred_speed(preferred_speedSEXP);
    Rcpp::traits::input_parameter< double >::type slowing_time(slowing_timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type current_speed(current_speedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type goal_distance(goal_distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(psUtility(a_preferred_speed, b_preferred_speed, preferred_speed, slowing_time, current_speed, goal_distance));
    return rcpp_result_gen;
END_RCPP
}
// gaUtility
NumericVector gaUtility(double b_goal_direction, double a_goal_direction, NumericVector goal_angles);
RcppExport SEXP _predped_gaUtility(SEXP b_goal_directionSEXP, SEXP a_goal_directionSEXP, SEXP goal_anglesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type b_goal_direction(b_goal_directionSEXP);
    Rcpp::traits::input_parameter< double >::type a_goal_direction(a_goal_directionSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type goal_angles(goal_anglesSEXP);
    rcpp_result_gen = Rcpp::wrap(gaUtility(b_goal_direction, a_goal_direction, goal_angles));
    return rcpp_result_gen;
END_RCPP
}
// caUtility
NumericVector caUtility(double b_current_direction, double a_current_direction, double blr_current_direction);
RcppExport SEXP _predped_caUtility(SEXP b_current_directionSEXP, SEXP a_current_directionSEXP, SEXP blr_current_directionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type b_current_direction(b_current_directionSEXP);
    Rcpp::traits::input_parameter< double >::type a_current_direction(a_current_directionSEXP);
    Rcpp::traits::input_parameter< double >::type blr_current_direction(blr_current_directionSEXP);
    rcpp_result_gen = Rcpp::wrap(caUtility(b_current_direction, a_current_direction, blr_current_direction));
    return rcpp_result_gen;
END_RCPP
}
// idUtility
NumericVector idUtility(double b_current_direction, double d_current_direction, double a_current_direction, LogicalVector id_ingroup, LogicalMatrix id_check, NumericMatrix id_distance, NumericVector impossible_utility);
RcppExport SEXP _predped_idUtility(SEXP b_current_directionSEXP, SEXP d_current_directionSEXP, SEXP a_current_directionSEXP, SEXP id_ingroupSEXP, SEXP id_checkSEXP, SEXP id_distanceSEXP, SEXP impossible_utilitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type b_current_direction(b_current_directionSEXP);
    Rcpp::traits::input_parameter< double >::type d_current_direction(d_current_directionSEXP);
    Rcpp::traits::input_parameter< double >::type a_current_direction(a_current_directionSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type id_ingroup(id_ingroupSEXP);
    Rcpp::traits::input_parameter< LogicalMatrix >::type id_check(id_checkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type id_distance(id_distanceSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type impossible_utility(impossible_utilitySEXP);
    rcpp_result_gen = Rcpp::wrap(idUtility(b_current_direction, d_current_direction, a_current_direction, id_ingroup, id_check, id_distance, impossible_utility));
    return rcpp_result_gen;
END_RCPP
}
// baUtility
NumericVector baUtility(double a_blocked, double b_blocked, NumericVector ba_angle, IntegerVector cone_id);
RcppExport SEXP _predped_baUtility(SEXP a_blockedSEXP, SEXP b_blockedSEXP, SEXP ba_angleSEXP, SEXP cone_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a_blocked(a_blockedSEXP);
    Rcpp::traits::input_parameter< double >::type b_blocked(b_blockedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ba_angle(ba_angleSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cone_id(cone_idSEXP);
    rcpp_result_gen = Rcpp::wrap(baUtility(a_blocked, b_blocked, ba_angle, cone_id));
    return rcpp_result_gen;
END_RCPP
}
// flUtility
NumericVector flUtility(double a_leader, double b_leader, double d_leader, NumericMatrix leaders, NumericMatrix distances);
RcppExport SEXP _predped_flUtility(SEXP a_leaderSEXP, SEXP b_leaderSEXP, SEXP d_leaderSEXP, SEXP leadersSEXP, SEXP distancesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a_leader(a_leaderSEXP);
    Rcpp::traits::input_parameter< double >::type b_leader(b_leaderSEXP);
    Rcpp::traits::input_parameter< double >::type d_leader(d_leaderSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type leaders(leadersSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type distances(distancesSEXP);
    rcpp_result_gen = Rcpp::wrap(flUtility(a_leader, b_leader, d_leader, leaders, distances));
    return rcpp_result_gen;
END_RCPP
}
// wbUtility
NumericVector wbUtility(double a_buddy, double b_buddy, NumericMatrix buddies, NumericMatrix distances);
RcppExport SEXP _predped_wbUtility(SEXP a_buddySEXP, SEXP b_buddySEXP, SEXP buddiesSEXP, SEXP distancesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a_buddy(a_buddySEXP);
    Rcpp::traits::input_parameter< double >::type b_buddy(b_buddySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type buddies(buddiesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type distances(distancesSEXP);
    rcpp_result_gen = Rcpp::wrap(wbUtility(a_buddy, b_buddy, buddies, distances));
    return rcpp_result_gen;
END_RCPP
}
// gc_utility_rcpp
NumericVector gc_utility_rcpp(double a_group_centroid, double b_group_centroid, double radius, NumericVector cell_distances, double stop_utility, int nped);
RcppExport SEXP _predped_gc_utility_rcpp(SEXP a_group_centroidSEXP, SEXP b_group_centroidSEXP, SEXP radiusSEXP, SEXP cell_distancesSEXP, SEXP stop_utilitySEXP, SEXP npedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a_group_centroid(a_group_centroidSEXP);
    Rcpp::traits::input_parameter< double >::type b_group_centroid(b_group_centroidSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cell_distances(cell_distancesSEXP);
    Rcpp::traits::input_parameter< double >::type stop_utility(stop_utilitySEXP);
    Rcpp::traits::input_parameter< int >::type nped(npedSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_utility_rcpp(a_group_centroid, b_group_centroid, radius, cell_distances, stop_utility, nped));
    return rcpp_result_gen;
END_RCPP
}
// vf_utility_rcpp
NumericVector vf_utility_rcpp(double b_visual_field, NumericVector relative_angles);
RcppExport SEXP _predped_vf_utility_rcpp(SEXP b_visual_fieldSEXP, SEXP relative_anglesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type b_visual_field(b_visual_fieldSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type relative_angles(relative_anglesSEXP);
    rcpp_result_gen = Rcpp::wrap(vf_utility_rcpp(b_visual_field, relative_angles));
    return rcpp_result_gen;
END_RCPP
}
// utility_rcpp
NumericVector utility_rcpp(DataFrame data, DataFrame parameters);
RcppExport SEXP _predped_utility_rcpp(SEXP dataSEXP, SEXP parametersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type parameters(parametersSEXP);
    rcpp_result_gen = Rcpp::wrap(utility_rcpp(data, parameters));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_predped_psUtility", (DL_FUNC) &_predped_psUtility, 6},
    {"_predped_gaUtility", (DL_FUNC) &_predped_gaUtility, 3},
    {"_predped_caUtility", (DL_FUNC) &_predped_caUtility, 3},
    {"_predped_idUtility", (DL_FUNC) &_predped_idUtility, 7},
    {"_predped_baUtility", (DL_FUNC) &_predped_baUtility, 4},
    {"_predped_flUtility", (DL_FUNC) &_predped_flUtility, 5},
    {"_predped_wbUtility", (DL_FUNC) &_predped_wbUtility, 4},
    {"_predped_gc_utility_rcpp", (DL_FUNC) &_predped_gc_utility_rcpp, 6},
    {"_predped_vf_utility_rcpp", (DL_FUNC) &_predped_vf_utility_rcpp, 2},
    {"_predped_utility_rcpp", (DL_FUNC) &_predped_utility_rcpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_predped(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
