# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

unique <- function(x) {
    .Call('_predped_unique', PACKAGE = 'predped', x)
}

#' Compute the min-log-likelihood
#' 
#' Rcpp alternative to \code{\link[predped]{mll}}. Be wary: This version does 
#' not automatically add the motion variables to the data if not present in 
#' the data, nor does it do any of the other preprocessing. It is therefore 
#' better not used as an alternative to the R version, but rather as an 
#' extension of it (as done automatically in predped). 
#'
#' @param data Data.frame containing at least "id", "time", "x", "y", "goal_x",
#' "goal_y", and "goal_id". If it does not have the utility variables yet, these
#' will add them to the data.frame.
#' @param parameters Numeric vector or matrix containing the parameters to be 
#' used. Should be specified in the same order as specified in 
#' \code{"parameter_names"}. If a matrix, each row should contain parameters to 
#' be estimated for each instance of "id" separately.
#' @param parameter_names Character vector containing the parameters that you 
#' want to estimate. Defaults to all parameters defined in
#' \code{\link[predped]{params_from_csv}}. Whenever not all parameters are used,
#' the excluded parameters are assumed to have a value of 0.
#' @param transform Logical denoting whether to transform the provided parameters
#' from the real axis to the bounded scales imposed on the parameters within 
#' \code{predped}. Defaults to \code{TRUE}.
#' @param bounds Matrix containing the lower and upper bounds of the parameters
#' in its first and second column respectively. Additionally, rownames should 
#' denote for which parameter a certain pair represents the bounds. Only used 
#' when \code{transform = TRUE}. Defaults to the default bounds of \code{predped}.
#' @param ... Additional arguments passed on to \code{\link[predped]{add_motion_variables}}.
#' In a typical estimation situation, these motion variables should already be 
#' in \code{data}.
#' 
#' @return Min-log-likelihood per person in the dataset.
#' 
#' @export 
mll_rcpp <- function(data, parameters, parameter_names, ids) {
    .Call('_predped_mll_rcpp', PACKAGE = 'predped', data, parameters, parameter_names, ids)
}

psUtility <- function(a_preferred_speed, b_preferred_speed, preferred_speed, slowing_time, current_speed, goal_distance) {
    .Call('_predped_psUtility', PACKAGE = 'predped', a_preferred_speed, b_preferred_speed, preferred_speed, slowing_time, current_speed, goal_distance)
}

gaUtility <- function(b_goal_direction, a_goal_direction, goal_angles) {
    .Call('_predped_gaUtility', PACKAGE = 'predped', b_goal_direction, a_goal_direction, goal_angles)
}

caUtility <- function(b_current_direction, a_current_direction, blr_current_direction) {
    .Call('_predped_caUtility', PACKAGE = 'predped', b_current_direction, a_current_direction, blr_current_direction)
}

idUtility <- function(b_current_direction, d_current_direction, a_current_direction, id_ingroup, id_check, id_distance, impossible_utility) {
    .Call('_predped_idUtility', PACKAGE = 'predped', b_current_direction, d_current_direction, a_current_direction, id_ingroup, id_check, id_distance, impossible_utility)
}

baUtility <- function(a_blocked, b_blocked, ba_angle, cone_id) {
    .Call('_predped_baUtility', PACKAGE = 'predped', a_blocked, b_blocked, ba_angle, cone_id)
}

flUtility <- function(a_leader, b_leader, d_leader, leaders, distances) {
    .Call('_predped_flUtility', PACKAGE = 'predped', a_leader, b_leader, d_leader, leaders, distances)
}

wbUtility <- function(a_buddy, b_buddy, buddies, distances) {
    .Call('_predped_wbUtility', PACKAGE = 'predped', a_buddy, b_buddy, buddies, distances)
}

#' Group centroid utility
#'
#' Rcpp alternative for the group centroid utility function. 
#' 
#' @param a_gc Numeric denoting the power to which to take the utility.
#' @param b_gc Numeric denoting the slope of the utility function.
#' @param radius Numeric denoting the radius of the agent.
#' @param cell_dist Numeric vector denoting the distance of each cell in the 
#' \code{centers} to the predicted group centroid.
#' @param stop_utility Numeric denoting the utility of stopping. Is used to 
#' ensure the agents do not freeze when they are too far away from each other. 
#' @param nped Numeric denoting the number of ingroup members. 
#' 
#' @return Numeric vector containing the group-centroid-related utility for each 
#' cell. 
#' 
#' @seealso 
#' \code{\link[predped]{distance_group_centroid}},
#' \code{\link[predped]{params_from_csv}},
#' \code{\link[predped]{utility}}
#' 
#' @rdname gc_utility_rcpp
#' 
#' @export
gc_utility_rcpp <- function(a_group_centroid, b_group_centroid, radius, cell_distances, stop_utility, nped) {
    .Call('_predped_gc_utility_rcpp', PACKAGE = 'predped', a_group_centroid, b_group_centroid, radius, cell_distances, stop_utility, nped)
}

#' Discrete visual field utility
#' 
#' Rcpp alternative to the \code{vf_utility_discrete} function.
#' 
#' The idea of this utility function is that it doesn't matter at which angle 
#' you see a group member within the visual field, as long as you see them. 
#' This translates to a discrete added disutility whenever the group member 
#' falls inside the non-visual zone behind the agent.
#' 
#' @param b_vf Numeric denoting the slope of the utility function. 
#' @param rel_angles Numeric vector containing the relative angle from each cell 
#' center to the predicted positions of the group members. Typically output of 
#' \code{\link[predped]{get_angle}}. 
#' 
#' @return Numeric vector containing the utility attributed to keeping the 
#' group members within your visual field. Returns 0's if the agent does not 
#' have any additional group members.
#' 
#' @seealso 
#' \code{\link[predped]{get_angles}},
#' \code{\link[predped]{utility}},
#' \code{\link[predped]{vf_utility_continuous}}
#' 
#' @rdname vf_utility_rcpp
#' 
#' @export
vf_utility_rcpp <- function(b_visual_field, relative_angles) {
    .Call('_predped_vf_utility_rcpp', PACKAGE = 'predped', b_visual_field, relative_angles)
}

#' Utility
#'
#' This function is the Rcpp equivalent of \code{\link[predped]{utility}}. It
#' takes in a dataframe containing all of the relevant values for computing the
#' utility, as well as a dataframe containing the parameters. Heavily depends 
#' on the \code{m4ma} package.
#' 
#' @param object Dataframe containing all of the needed information to compute 
#' the utilities. Typically output of the 
#' \code{\link[predped]{compute_utility_variables}} function.
#' @param parameters Dataframe containing the parameters of the agent. Should 
#' conform to the naming conventions mentioned in 
#' \code{\link[predped]{params_from_csv}}.
#' 
#' @return Numeric vector denoting the (dis)utility of moving to each of the 
#' potential cells.
#' 
#' @seealso 
#' \code{\link[predped]{simulate,predped-method}},
#' \code{\link[predped]{simulate,state-method}},
#' \code{\link[predped]{update,agent-method}},
#' \code{\link[predped]{update,state-method}},
#' \code{\link[predped]{utility,agent-method}},
#' \code{\link[predped]{compute_utility_variables}},
#' \code{\link[predped]{params_from_csv}},
#' \code{\link[predped]{update_position}}
#' 
#' @rdname utility_rcpp
#' 
utility_rcpp <- function(data, parameters) {
    .Call('_predped_utility_rcpp', PACKAGE = 'predped', data, parameters)
}

